#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKER_TAG" = "foxy" ] ; then
docker build --build-arg ROSDISTRO=$DOCKER_TAG --build-arg ROS_BASE_TAG=$DOCKER_TAG -t $IMAGE_NAME .
else
docker build --build-arg ROSDISTRO=$DOCKER_TAG --build-arg ROS_BASE_TAG=$DOCKER_TAG-perception -t $IMAGE_NAME .
fi
