# rosindustrial/ros-robot-nvidia:lunar-8.0
FROM rosindustrial/ros-base-nvidia:lunar-8.0
LABEL maintainer "Austin.Deric@SwRI.org"

RUN apt-get update && apt-get install -y \
    ros-lunar-robot \
&& rm -rf /var/lib/apt/lists/*
