# rosindustrial/core:kinetic
FROM ros:kinetic-robot
MAINTAINER Austin.Deric@gmail.com
RUN apt-get update && apt-get install -y \
    ros-kinetic-industrial-core \
    python-wstool \
    python-catkin-tools \
    liblapack-dev \
    libblas-dev \
    sudo
