# rosindustrial/noether-webtools:kinetic
FROM rosindustrial/noether:kinetic
MAINTAINER Austin.Deric@gmail.com
RUN apt-get update && apt-get install -y \
  ros-kinetic-rosbridge-suite \
  ros-kinetic-tf2-web-republisher
