# rosindustrial/core:kinetic
FROM ros:indigo
MAINTAINER "Austin.Deric@gmail.com"
RUN apt-get update && apt-get install -y \
    python-wstool \
    python-catkin-tools \
    ros-indigo-moveit \
    ros-indigo-openni2-camera \
    ros-indigo-perception-pcl \
    ros-indigo-roslint \
    ros-indigo-rqt-gui \
    ros-indigo-rqt-gui-cpp \
    ros-indigo-rqt-gui-py

